### ISSUE TITLE
There is no settings for this plugin but its calling get_config('report_rubric_list' , 'displayname')

### ISSUE THREAD

**Issue by rjnl** [mackensen/moodle-report_rubric_list#3]
There is no setting "displayname".

https://github.com/LafColITS/moodle-report_rubric_list/blob/25cfcceda75d5fdf90e8d140fa77c9852934a319/index.php#L47

It produces a title such as shown below:
![image](https://github.com/LafColITS/moodle-report_rubric_list/assets/4531184/fd3f94cc-e3b5-41f9-ab97-0b54ad4bfc8d)

**Comment by mackensen** [comment]
Ugh, straight-up copy/paste fail from another plugin I maintain. That should just be a lang string. Good catch!
